# Generated by Django 2.2.1 on 2019-06-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_notice', models.CharField(max_length=200)),
                ('due_date', models.DateTimeField()),
                ('body_notice', models.TextField()),
            ],
        ),
    ]
