# Generated by Django 2.2.1 on 2019-06-05 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190605_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticeboard',
            old_name='body',
            new_name='body_nb',
        ),
        migrations.RenameField(
            model_name='noticeboard',
            old_name='title',
            new_name='title_nb',
        ),
    ]
