# Generated by Django 2.2.1 on 2019-06-05 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190605_1904'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NoticeBoard',
        ),
    ]
